### ISSUE TITLE
DCNN Embeddings and Folding

### ISSUE THREAD

**Issue by sarpaykent** [theocjr/social-media-forensics#2]
Hello, I enjoyed reading your paper "A Needle in a Haystack? Harnessing Onomatopoeia and User-specific Stylometrics for Authorship Attribution of Micro-messages". I would like to run the CNNs on my dataset but I'm having a hard time where [DCNN.embeddings](https://github.com/theocjr/social-media-forensics/blob/15e98b0f7f082613554bf4a47366653beab4fb90/microblog_authorship_attribution/deep_learning/cnn/DynamicCNN/networks.py#L26) and DCNN.folding are coming from. I couldn't see these files under the DCNN folder. Is there a possibility that they are missing?

Regards,

**Comment by theocjr** [comment]
Hi


The code you look for is in https://github.com/FredericGodin/DynamicCNN .
The ones (networks.py and convolutions.py) on my repositories are the ones
I edited.


Have fun

Antonio


-----
"Ignorance more frequently begets confidence than does knowledge: it is
those who know little, not those who know much, who so positively assert
that this or that problem will never be solved by science."
Charles Darwin

**Comment by sarpaykent** [comment]
Thank you for the clarification!

**Comment by theocjr** [comment]
You're welcome. I'll update the repository with the ones left. Thank you
for letting me know.

-----
"Ignorance more frequently begets confidence than does knowledge: it is
those who know little, not those who know much, who so positively assert
that this or that problem will never be solved by science."
Charles Darwin
